{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "remote",
    "version": "1.0.0-snapshot-ofuscated-41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-snapshot-ofuscated-41.aar",
          "url": "remote-1.0.0-snapshot-ofuscated-41.aar",
          "size": 73682,
          "sha512": "ef790af375d86b9b848ee4d140dce5592632c3847ed8f83b90c70299f3fc4efb8bc7f9de07d0eea2c767ad63481d76f674959c3cc4b0af8001649cc9bb7a649c",
          "sha256": "c6ef05603af81059afe1a904bca36f7b5dd49c717c30038cab181ae0d02f0b66",
          "sha1": "0db036f714716eb81406212ccb55409504e9cceb",
          "md5": "da33c447a4944c57c07e31106692bd10"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-snapshot-ofuscated-41.aar",
          "url": "remote-1.0.0-snapshot-ofuscated-41.aar",
          "size": 73682,
          "sha512": "ef790af375d86b9b848ee4d140dce5592632c3847ed8f83b90c70299f3fc4efb8bc7f9de07d0eea2c767ad63481d76f674959c3cc4b0af8001649cc9bb7a649c",
          "sha256": "c6ef05603af81059afe1a904bca36f7b5dd49c717c30038cab181ae0d02f0b66",
          "sha1": "0db036f714716eb81406212ccb55409504e9cceb",
          "md5": "da33c447a4944c57c07e31106692bd10"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-1.0.0-snapshot-ofuscated-41-sources.jar",
          "url": "remote-1.0.0-snapshot-ofuscated-41-sources.jar",
          "size": 39440,
          "sha512": "695070fe3a9fa630d5956cb441829e0deeb2777f8b6f542dfd0d06ae777633d6c0d55f4e35fb0b59b2370e10b6a284aec2b6e4bd626232b55a08314cae62d233",
          "sha256": "1fb358c3a4fde521df8268b9132b742d1d6d0003d047c493cd6692ed5a9cb671",
          "sha1": "6a9111e3e454cc455f971ca79efa9e1affe33e55",
          "md5": "b498b5a4e5c2ed04e9f646ef770b9350"
        }
      ]
    }
  ]
}
