{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "network",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "network-3.0.1.aar",
          "url": "network-3.0.1.aar",
          "size": 58003,
          "sha512": "11a6e1a27251f6e63e06337aabb74e64a7b34f69275b4a02ba785195dc96beb017e2df9e6078c704ea5ac7b01f3213db2cbb4eea3a139550154321affae029e6",
          "sha256": "f4005391460aeddae763563080593f2387c9e0578b0a1307f1bb5499fdf3f253",
          "sha1": "8947aa4c4c926b9fe9d542ea860f1d4aaa96dba6",
          "md5": "588c4d1c6d7a9548263ea2430ffe10b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "network-3.0.1.aar",
          "url": "network-3.0.1.aar",
          "size": 58003,
          "sha512": "11a6e1a27251f6e63e06337aabb74e64a7b34f69275b4a02ba785195dc96beb017e2df9e6078c704ea5ac7b01f3213db2cbb4eea3a139550154321affae029e6",
          "sha256": "f4005391460aeddae763563080593f2387c9e0578b0a1307f1bb5499fdf3f253",
          "sha1": "8947aa4c4c926b9fe9d542ea860f1d4aaa96dba6",
          "md5": "588c4d1c6d7a9548263ea2430ffe10b0"
        }
      ]
    }
  ]
}
