{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "local",
    "version": "1.0.0-snapshot-ofuscated-42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0-snapshot-ofuscated-42.aar",
          "url": "local-1.0.0-snapshot-ofuscated-42.aar",
          "size": 10522,
          "sha512": "45f5991813209c019593944d7e5ec680d7ae939c19bccde5f6a01a8695b691f32b6341bb4cd612925c781f9e85f820c7e1f78a17d8d217574fb31d3f10731159",
          "sha256": "8a05cdcd24461e22ae31cd11573dd0804fbed30a37e5202989f6b14c566dec3d",
          "sha1": "7259d08def9e348226f54f93a16b17241b630d3d",
          "md5": "7b45d0e309860c5295287aeccb7fa58b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-42"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0-snapshot-ofuscated-42.aar",
          "url": "local-1.0.0-snapshot-ofuscated-42.aar",
          "size": 10522,
          "sha512": "45f5991813209c019593944d7e5ec680d7ae939c19bccde5f6a01a8695b691f32b6341bb4cd612925c781f9e85f820c7e1f78a17d8d217574fb31d3f10731159",
          "sha256": "8a05cdcd24461e22ae31cd11573dd0804fbed30a37e5202989f6b14c566dec3d",
          "sha1": "7259d08def9e348226f54f93a16b17241b630d3d",
          "md5": "7b45d0e309860c5295287aeccb7fa58b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "local-1.0.0-snapshot-ofuscated-42-sources.jar",
          "url": "local-1.0.0-snapshot-ofuscated-42-sources.jar",
          "size": 8632,
          "sha512": "78c3bd0066aedd719cdd096e4a77d08517cbd0dd1cc09df19cfea0bd9f0bfd7a593599441e51598595fff6a99f36845b92414abeed20042f089674bd1be267a2",
          "sha256": "14101665ce36c7bb4dce3ed4fa4de910f8e26aa8c210d866dbbba6bd738a4788",
          "sha1": "495de7b124ae131a82a3768967f0380b164be876",
          "md5": "3ff3c1f6cc6352bb10563d82923b2910"
        }
      ]
    }
  ]
}
