{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "remote",
    "version": "1.0.0-ofuscated",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-ofuscated.aar",
          "url": "remote-1.0.0-ofuscated.aar",
          "size": 22090,
          "sha512": "9913b03b6bf1993177abae20a1d1fcc4171818f12366958dd756fde1f932728279a03aa1e4815c20930cd70642ef6a485ad966c61b205ddbc5325b4b65668e40",
          "sha256": "12b3066e1f8826c13a6bfd2c94dd744cfbce13fe04f0b2d9118ca787398a4c1f",
          "sha1": "9d20ec36768dfda1b45a3d19dc33ff4a0d87294e",
          "md5": "cf1c85a59809750f4d252acfd1b523d9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-ofuscated.aar",
          "url": "remote-1.0.0-ofuscated.aar",
          "size": 22090,
          "sha512": "9913b03b6bf1993177abae20a1d1fcc4171818f12366958dd756fde1f932728279a03aa1e4815c20930cd70642ef6a485ad966c61b205ddbc5325b4b65668e40",
          "sha256": "12b3066e1f8826c13a6bfd2c94dd744cfbce13fe04f0b2d9118ca787398a4c1f",
          "sha1": "9d20ec36768dfda1b45a3d19dc33ff4a0d87294e",
          "md5": "cf1c85a59809750f4d252acfd1b523d9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-1.0.0-ofuscated-sources.jar",
          "url": "remote-1.0.0-ofuscated-sources.jar",
          "size": 14159,
          "sha512": "51f7bd905182165111c64a2ed023ae9860d3cda06fc9211dcd0003dc88fddc370fe513fb4b1a5a11a6f4d928203ae2500c94301e72bd3bea124987e7db15fe2c",
          "sha256": "c22c297e471cfd66e64074f0b48b3871c7b21e9749b18a0d80b02e6ef6e53ee3",
          "sha1": "8db7c5afc3ee83ae7f92ad0b6b9f0dd1361c0f6d",
          "md5": "29b57a229a69ca8ff434ad41aad9b970"
        }
      ]
    }
  ]
}
