{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "remote",
    "version": "1.0.0-snapshot-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-snapshot-3.aar",
          "url": "remote-1.0.0-snapshot-3.aar",
          "size": 32402,
          "sha512": "2cc5fb2cfc4cc5f8fc9e0dbe6fdee114d243a11bbcdf0d0d9f07f528684c5eae8239ad21c3b6d7f2048a896b04ff86f85b59c8318be5e86c45998fcb38ddd082",
          "sha256": "129fb8dcb58ba5319e6dca0a7ac3ba9732ef52ecaa779672426655890d89ac2f",
          "sha1": "79d10e017030ea45dca7591efad314b294a51b51",
          "md5": "498875e07166b4638c5ef44a21323ff3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-snapshot-3.aar",
          "url": "remote-1.0.0-snapshot-3.aar",
          "size": 32402,
          "sha512": "2cc5fb2cfc4cc5f8fc9e0dbe6fdee114d243a11bbcdf0d0d9f07f528684c5eae8239ad21c3b6d7f2048a896b04ff86f85b59c8318be5e86c45998fcb38ddd082",
          "sha256": "129fb8dcb58ba5319e6dca0a7ac3ba9732ef52ecaa779672426655890d89ac2f",
          "sha1": "79d10e017030ea45dca7591efad314b294a51b51",
          "md5": "498875e07166b4638c5ef44a21323ff3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-1.0.0-snapshot-3-sources.jar",
          "url": "remote-1.0.0-snapshot-3-sources.jar",
          "size": 15687,
          "sha512": "d3f55db5ee40f25e148b4384244fd330f9c82e26ec1634fb7772049d7e9dccbeeb760f6d85ff7f88051f8bb2673dd3baca8ff431ce6da588271a559f208d243f",
          "sha256": "572920c4a30ccd80b8eafeb79c1fa71d9a0364c0b6ab3dd70018b36c16b7c832",
          "sha1": "67d5a4fb237aa48d7b16bf898fb4b033408b4462",
          "md5": "da0474b1e8267e52bc95a8d3e92927d9"
        }
      ]
    }
  ]
}
