{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "commons",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0.0.aar",
          "url": "commons-1.0.0.aar",
          "size": 19741,
          "sha512": "86e3c688602b9c793e37358743eb9ba57dabb11386cc309384a355e4611df9a40e7a5b866e2b11be63ab1af1ee994f01e1fea2136dc6a73f7f151e5955c8755b",
          "sha256": "c5015a660f60c2ff64c1bc5a1fb5ffe269c1172416e1d13a033539c4a77992a5",
          "sha1": "6f62f9d1a1190952da5d7f9b2406ff7571ce3685",
          "md5": "7f6d558c503c3711522c531a18a2e842"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0.0.aar",
          "url": "commons-1.0.0.aar",
          "size": 19741,
          "sha512": "86e3c688602b9c793e37358743eb9ba57dabb11386cc309384a355e4611df9a40e7a5b866e2b11be63ab1af1ee994f01e1fea2136dc6a73f7f151e5955c8755b",
          "sha256": "c5015a660f60c2ff64c1bc5a1fb5ffe269c1172416e1d13a033539c4a77992a5",
          "sha1": "6f62f9d1a1190952da5d7f9b2406ff7571ce3685",
          "md5": "7f6d558c503c3711522c531a18a2e842"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "commons-1.0.0-sources.jar",
          "url": "commons-1.0.0-sources.jar",
          "size": 10529,
          "sha512": "cdc66015a7b102dea0f9a30bdb294504846727f02aae9790be7b99df4b3fd40ea5d1bfa60e6e997a77f448eb87d1dffb566a42769ad95f2a542f063904849c55",
          "sha256": "a12eeda6274fd0fbf3d3c269bce49f40f55db2f09fc20b2f2834cb72e8f8e272",
          "sha1": "0664f2222ad14c337920669bc540541b578d3967",
          "md5": "72026a270486029fc973148329485a2c"
        }
      ]
    }
  ]
}
