{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "core",
    "version": "1.0.0-snapshot-ofuscated-13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-snapshot-ofuscated-13.aar",
          "url": "core-1.0.0-snapshot-ofuscated-13.aar",
          "size": 376333,
          "sha512": "e832d882f4e872fed859493bb7443c0ed2114fa1f2f5e07be49ca7ca91b4bbd41f443a62ddb1f190eeed298bc46b1c484b8748fbf74177fc7e36502ec2419d72",
          "sha256": "fd8372f9838d1c0fdcd75c8aefa9d5044e2705032b77e8dc08304e3141ddb754",
          "sha1": "7c01e85d84a2db702d403f25d38d9796c287e6e2",
          "md5": "94d553a69fff9e6ffee5253ec7e2a267"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "designSystem",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "facetec",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "docCore",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "remote",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "local",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "deviceIntelligence",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "liveness2d",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-12"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-snapshot-ofuscated-13.aar",
          "url": "core-1.0.0-snapshot-ofuscated-13.aar",
          "size": 376333,
          "sha512": "e832d882f4e872fed859493bb7443c0ed2114fa1f2f5e07be49ca7ca91b4bbd41f443a62ddb1f190eeed298bc46b1c484b8748fbf74177fc7e36502ec2419d72",
          "sha256": "fd8372f9838d1c0fdcd75c8aefa9d5044e2705032b77e8dc08304e3141ddb754",
          "sha1": "7c01e85d84a2db702d403f25d38d9796c287e6e2",
          "md5": "94d553a69fff9e6ffee5253ec7e2a267"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.0.0-snapshot-ofuscated-13-sources.jar",
          "url": "core-1.0.0-snapshot-ofuscated-13-sources.jar",
          "size": 135168,
          "sha512": "f0a05d668ef5dd30495193c352b080224b72379630aac1a9adecdfb25dd67edee3e0f921f1ffbb19fbfc517f6803aa4053a1fe0f7096d3d7d196a18594200321",
          "sha256": "7f8fd6715b9e7a4d0b2d21e1feadd032ff24a991d7c3a9908c2a7f5721ce7c62",
          "sha1": "0ddcda555767be7e571b00d768f620593521b1d5",
          "md5": "115fb3f6843ce0df8572f5c20c7fbec5"
        }
      ]
    }
  ]
}
