{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "liveness2d",
    "version": "1.0.0-snapshot-ofuscated-31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-1.0.0-snapshot-ofuscated-31.aar",
          "url": "liveness2d-1.0.0-snapshot-ofuscated-31.aar",
          "size": 187960,
          "sha512": "f432dd6c1b9e02229707b23322740f94cf72e24071a629e2b8b8acb7d5e19cc2cf446be6abdf59a30590df5415ea17b163f8c34fa02fe9ad8917f821eb6e7e60",
          "sha256": "42273607892217d238f7462a79e53fe1f317d1f0aeda4d78276611372e3115ef",
          "sha1": "31f9f3b31d21077983a0f1f5f344c066659636a9",
          "md5": "3a27c8f7d025a996669d600074b7d8c4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.36.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.11.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "designSystem",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-31"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-31"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-31"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "remote",
          "version": {
            "requires": "1.0.0-snapshot-ofuscated-31"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-1.0.0-snapshot-ofuscated-31.aar",
          "url": "liveness2d-1.0.0-snapshot-ofuscated-31.aar",
          "size": 187960,
          "sha512": "f432dd6c1b9e02229707b23322740f94cf72e24071a629e2b8b8acb7d5e19cc2cf446be6abdf59a30590df5415ea17b163f8c34fa02fe9ad8917f821eb6e7e60",
          "sha256": "42273607892217d238f7462a79e53fe1f317d1f0aeda4d78276611372e3115ef",
          "sha1": "31f9f3b31d21077983a0f1f5f344c066659636a9",
          "md5": "3a27c8f7d025a996669d600074b7d8c4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "liveness2d-1.0.0-snapshot-ofuscated-31-sources.jar",
          "url": "liveness2d-1.0.0-snapshot-ofuscated-31-sources.jar",
          "size": 56074,
          "sha512": "e52c806925865c4cf7591d064a3d4b1a726505b536cee4147926c452dec02248d1bd39e6d82b2fc7e2fead309cfa66640a39803409079536f89fec95dc2105fc",
          "sha256": "cf1b9013b6923f6d5abe59decfc2e8e6a9f0562471ab7ae4cd6a597e14638e33",
          "sha1": "921cdfe0faea560b7449d682fb46d88c06746d8c",
          "md5": "f7b56de35e0f25d6db8790d01a89b62b"
        }
      ]
    }
  ]
}
