{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "commons",
    "version": "1.0.0-ofuscated-13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0.0-ofuscated-13.aar",
          "url": "commons-1.0.0-ofuscated-13.aar",
          "size": 20405,
          "sha512": "8bde254fa9d0ec9491e3882c2bd8032da0b4f8580b6218136fc32e83b008d1d8cd194e14bab24a4a74576da2443b96987b11bf4a7899778949f28207b9d19605",
          "sha256": "bf52a80b988f47bd48f097db111cfe5b4c489fc9e3440dc2ee26f30129fbe4df",
          "sha1": "880745abbaf44c0d1c5a303afa47165f8dad5bfb",
          "md5": "d8b9c3dd792b226783780548062eaae3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0.0-ofuscated-13.aar",
          "url": "commons-1.0.0-ofuscated-13.aar",
          "size": 20405,
          "sha512": "8bde254fa9d0ec9491e3882c2bd8032da0b4f8580b6218136fc32e83b008d1d8cd194e14bab24a4a74576da2443b96987b11bf4a7899778949f28207b9d19605",
          "sha256": "bf52a80b988f47bd48f097db111cfe5b4c489fc9e3440dc2ee26f30129fbe4df",
          "sha1": "880745abbaf44c0d1c5a303afa47165f8dad5bfb",
          "md5": "d8b9c3dd792b226783780548062eaae3"
        }
      ]
    }
  ]
}
