{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "deviceIntelligence",
    "version": "1.0.0-ofuscated-13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "deviceIntelligence-1.0.0-ofuscated-13.aar",
          "url": "deviceIntelligence-1.0.0-ofuscated-13.aar",
          "size": 97226,
          "sha512": "7b5e2bae6de45680ee9b984dba61a67357a73bbb90fbcea6561651111e45c70b252898d6c1e9c30dcc2c1e72d94a6474fe69d2ed20b7888c67421be5e4faf64c",
          "sha256": "6733373f0e0ab784de67a6f7bf60f1d8e999f912f8ed226618db413b05ce93b5",
          "sha1": "18c4d60853029f3753fa55544f2636f8fbf69bbe",
          "md5": "d9ea47b4a941987bce64ce3928e68e39"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "remote",
          "version": {
            "requires": "1.0.0-ofuscated-13"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "local",
          "version": {
            "requires": "1.0.0-ofuscated-13"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "deviceIntelligence-1.0.0-ofuscated-13.aar",
          "url": "deviceIntelligence-1.0.0-ofuscated-13.aar",
          "size": 97226,
          "sha512": "7b5e2bae6de45680ee9b984dba61a67357a73bbb90fbcea6561651111e45c70b252898d6c1e9c30dcc2c1e72d94a6474fe69d2ed20b7888c67421be5e4faf64c",
          "sha256": "6733373f0e0ab784de67a6f7bf60f1d8e999f912f8ed226618db413b05ce93b5",
          "sha1": "18c4d60853029f3753fa55544f2636f8fbf69bbe",
          "md5": "d9ea47b4a941987bce64ce3928e68e39"
        }
      ]
    }
  ]
}
