{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "local",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0.aar",
          "url": "local-1.0.0.aar",
          "size": 10329,
          "sha512": "a84ec6f7b05ebc1bc8d47471ee4efc902907d9bffabdd615e183f9620d533679c1a277f224a4494e2bd2c9ad328ecb3e9c5903cdad3bfffe0e09866d8b0baf62",
          "sha256": "a60bd3fb337ee269de60b41f25492db1123f42e3c863d681a093958ab25c05d9",
          "sha1": "61c18c03ed59fc0b019052558eac1986d2231ccc",
          "md5": "e59d54f7a5a9db908a16b6c174d1d33f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0.aar",
          "url": "local-1.0.0.aar",
          "size": 10329,
          "sha512": "a84ec6f7b05ebc1bc8d47471ee4efc902907d9bffabdd615e183f9620d533679c1a277f224a4494e2bd2c9ad328ecb3e9c5903cdad3bfffe0e09866d8b0baf62",
          "sha256": "a60bd3fb337ee269de60b41f25492db1123f42e3c863d681a093958ab25c05d9",
          "sha1": "61c18c03ed59fc0b019052558eac1986d2231ccc",
          "md5": "e59d54f7a5a9db908a16b6c174d1d33f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "local-1.0.0-sources.jar",
          "url": "local-1.0.0-sources.jar",
          "size": 5925,
          "sha512": "95027046a03c2c5460252e2219cde65fa570ab207760630536dc01a09cfec11636e12fe5cf8462f439edc16688af5f7e88804cb0bc02677b6bbc3905c421ef22",
          "sha256": "00c7ae02a79fc9108993d19b755b1aab4cb2941dd03f7a06e1d2ea7ebd55b955",
          "sha1": "07d09923d8e5014df4ea552a88f0eda30e03d02f",
          "md5": "2109b105214ebcbf93f2cbf8359dafa2"
        }
      ]
    }
  ]
}
