{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "core",
    "version": "1.0.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-snapshot-2.aar",
          "url": "core-1.0.0-snapshot-2.aar",
          "size": 523771,
          "sha512": "2992ca88b6f802021a3c72ae1f9ccde7aa11bd077a3e03da2274a8e897604718f47808a4577d37d362506e743b1d334e8c47bc2b6f26f8c3128427f2f3bf6510",
          "sha256": "20be53e4c7d0aa3e0ec578dc01f9c297254c531e6478205a71c0400981a590e0",
          "sha1": "062895cf6adfebed8f0cf3210b855000365a37fc",
          "md5": "1ca84ba8ef58acc355968bedd4c06e2e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.09.03"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-work",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "multimedia",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "designSystem",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "facetec",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "docCore",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "iproov",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "remote",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "local",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "deviceIntelligence",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "liveness2d",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-snapshot-2.aar",
          "url": "core-1.0.0-snapshot-2.aar",
          "size": 523771,
          "sha512": "2992ca88b6f802021a3c72ae1f9ccde7aa11bd077a3e03da2274a8e897604718f47808a4577d37d362506e743b1d334e8c47bc2b6f26f8c3128427f2f3bf6510",
          "sha256": "20be53e4c7d0aa3e0ec578dc01f9c297254c531e6478205a71c0400981a590e0",
          "sha1": "062895cf6adfebed8f0cf3210b855000365a37fc",
          "md5": "1ca84ba8ef58acc355968bedd4c06e2e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-1.0.0-snapshot-2-sources.jar",
          "url": "core-1.0.0-snapshot-2-sources.jar",
          "size": 167898,
          "sha512": "3df1250f3833f1378a969cf7ade6e93e539ec238e64535b46fac21a62feb69a961de9835c88e6e9f4341ee1ccaabcfa79d3a29eb3fcd41a9cd74536b21468710",
          "sha256": "311c75c6efc2c93a41c0f80a6c822e864577a24ebec23babc6e89de54caed064",
          "sha1": "37423ebd5061ff78821bf0730e297e0766d19a38",
          "md5": "134c32ecd642e10199003abc645068fb"
        }
      ]
    }
  ]
}
