{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "network",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "network-2.0.1.aar",
          "url": "network-2.0.1.aar",
          "size": 56827,
          "sha512": "809e41db0d3143acaef76f870693787ef61b278b5ad4e074a52b9533bd3fac9364e1ce1a1baaecb611e5dfd09457015b5dc3088fee1b83de706f79c092445409",
          "sha256": "a98d61b9d149302d5e13a20ba306827be566afd9c8e71ded4cdc62ea91b2ce7b",
          "sha1": "f7ae7a4858a9ffb1e654dbc8de2ca157bacf81d4",
          "md5": "4596133ac11ff14edeabc1671cd3c850"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "network-2.0.1.aar",
          "url": "network-2.0.1.aar",
          "size": 56827,
          "sha512": "809e41db0d3143acaef76f870693787ef61b278b5ad4e074a52b9533bd3fac9364e1ce1a1baaecb611e5dfd09457015b5dc3088fee1b83de706f79c092445409",
          "sha256": "a98d61b9d149302d5e13a20ba306827be566afd9c8e71ded4cdc62ea91b2ce7b",
          "sha1": "f7ae7a4858a9ffb1e654dbc8de2ca157bacf81d4",
          "md5": "4596133ac11ff14edeabc1671cd3c850"
        }
      ]
    }
  ]
}
