{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "network",
    "version": "2.1.0-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "network-2.1.0-snapshot.aar",
          "url": "network-2.1.0-snapshot.aar",
          "size": 21302,
          "sha512": "ddf92bf57e8c754243f4feb587cd8aa303975a0e0543c857991569d507a7c7c96946be225acb64a3d9f65bc8af38b54e79ccef2a7f258c235f5a48e9bb0d4e44",
          "sha256": "8e266ab537e1fd5232bfdb6dd79a8523ca5ba1c39057ce2fe70491844e9675f4",
          "sha1": "5d5edf28346a479021f8bbd557ddae484c0cd4cf",
          "md5": "3d66b36c5614b977610c2e9fda23bc2e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "network-2.1.0-snapshot.aar",
          "url": "network-2.1.0-snapshot.aar",
          "size": 21302,
          "sha512": "ddf92bf57e8c754243f4feb587cd8aa303975a0e0543c857991569d507a7c7c96946be225acb64a3d9f65bc8af38b54e79ccef2a7f258c235f5a48e9bb0d4e44",
          "sha256": "8e266ab537e1fd5232bfdb6dd79a8523ca5ba1c39057ce2fe70491844e9675f4",
          "sha1": "5d5edf28346a479021f8bbd557ddae484c0cd4cf",
          "md5": "3d66b36c5614b977610c2e9fda23bc2e"
        }
      ]
    }
  ]
}
