{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "local",
    "version": "1.0.0-ofuscated-12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0-ofuscated-12.aar",
          "url": "local-1.0.0-ofuscated-12.aar",
          "size": 10526,
          "sha512": "d95bebf908316c229c387e00be1d36d6f29fcf84c3695b52c41158a619ee9f88c1939c37f32d8791032080a352045e0a0c1847fb38f640e04e31925701279ea9",
          "sha256": "3a76ec03a6b194790e5d7f38ea3d7f0e0ea9a1e76ccd69c8ff9cb81ef9a1f791",
          "sha1": "a7af1b7dae0662262e120d9d3084037c9d8bf6f8",
          "md5": "ace876abd07d3ca29aab7efbac3fd312"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0-ofuscated-12"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0-ofuscated-12.aar",
          "url": "local-1.0.0-ofuscated-12.aar",
          "size": 10526,
          "sha512": "d95bebf908316c229c387e00be1d36d6f29fcf84c3695b52c41158a619ee9f88c1939c37f32d8791032080a352045e0a0c1847fb38f640e04e31925701279ea9",
          "sha256": "3a76ec03a6b194790e5d7f38ea3d7f0e0ea9a1e76ccd69c8ff9cb81ef9a1f791",
          "sha1": "a7af1b7dae0662262e120d9d3084037c9d8bf6f8",
          "md5": "ace876abd07d3ca29aab7efbac3fd312"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "local-1.0.0-ofuscated-12-sources.jar",
          "url": "local-1.0.0-ofuscated-12-sources.jar",
          "size": 5925,
          "sha512": "95027046a03c2c5460252e2219cde65fa570ab207760630536dc01a09cfec11636e12fe5cf8462f439edc16688af5f7e88804cb0bc02677b6bbc3905c421ef22",
          "sha256": "00c7ae02a79fc9108993d19b755b1aab4cb2941dd03f7a06e1d2ea7ebd55b955",
          "sha1": "07d09923d8e5014df4ea552a88f0eda30e03d02f",
          "md5": "2109b105214ebcbf93f2cbf8359dafa2"
        }
      ]
    }
  ]
}
