{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.0.aar",
          "url": "liveness2d-sdk-5.0.aar",
          "size": 2426942,
          "sha512": "aaa5d9b2b66f8e9fdeec30adf2615c50738bc5a9724461583a6a5de2d5c4a733876c76540257ad5f109bd1568848882d6781a7194deb7aa4feb27c16c42261c9",
          "sha256": "c602720339540e8ba02c179fadf8d1cca9b0ff203eb76154a1e230bc580d29f0",
          "sha1": "9fbf925b8835979e08f390f8a3afb1eaf071019e",
          "md5": "35a0c6e5b5367ee227e1a66ff18aaffe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.0.aar",
          "url": "liveness2d-sdk-5.0.aar",
          "size": 2426942,
          "sha512": "aaa5d9b2b66f8e9fdeec30adf2615c50738bc5a9724461583a6a5de2d5c4a733876c76540257ad5f109bd1568848882d6781a7194deb7aa4feb27c16c42261c9",
          "sha256": "c602720339540e8ba02c179fadf8d1cca9b0ff203eb76154a1e230bc580d29f0",
          "sha1": "9fbf925b8835979e08f390f8a3afb1eaf071019e",
          "md5": "35a0c6e5b5367ee227e1a66ff18aaffe"
        }
      ]
    }
  ]
}
