{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "remote",
    "version": "1.0.0-ofuscated-13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-ofuscated-13.aar",
          "url": "remote-1.0.0-ofuscated-13.aar",
          "size": 22142,
          "sha512": "d8bb227d91bb45634d813ecc07dd39155c199ea6da26ace60968ca28084cfb0f2e512a6c066be6cc841f465e0209d36abc12ffb1796de2d74ba5ad41f3ab9bf6",
          "sha256": "4a9d39b447aeaa9f9bf4121bf7543680b37e2f82097acc9ba07d77ec67f1ceba",
          "sha1": "8b6752f969685d8ba1d0c8bb8909452a9cf650ed",
          "md5": "95e3b1a0f4c9e381615d9cdf86de12fe"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-ofuscated-13.aar",
          "url": "remote-1.0.0-ofuscated-13.aar",
          "size": 22142,
          "sha512": "d8bb227d91bb45634d813ecc07dd39155c199ea6da26ace60968ca28084cfb0f2e512a6c066be6cc841f465e0209d36abc12ffb1796de2d74ba5ad41f3ab9bf6",
          "sha256": "4a9d39b447aeaa9f9bf4121bf7543680b37e2f82097acc9ba07d77ec67f1ceba",
          "sha1": "8b6752f969685d8ba1d0c8bb8909452a9cf650ed",
          "md5": "95e3b1a0f4c9e381615d9cdf86de12fe"
        }
      ]
    }
  ]
}
