{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.5.2.aar",
          "url": "liveness2d-sdk-5.5.2.aar",
          "size": 2542452,
          "sha512": "d81b213d258925f064e40d3a2ca3180d5afe4a37acf619080fff755a82615dafe1264e23c102235ac947fc21c6b121028b9f25e914b1fc20e830800076ba0fa5",
          "sha256": "0031044bc566808f3036fc8ec35db98cebcf2c5a676a80a6df2a3f20bd7199be",
          "sha1": "6512bab6ae4bb8424dde5d7d1dfa5bc2aec912b5",
          "md5": "31286d66a980b815712922fc031a7968"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.5.2.aar",
          "url": "liveness2d-sdk-5.5.2.aar",
          "size": 2542452,
          "sha512": "d81b213d258925f064e40d3a2ca3180d5afe4a37acf619080fff755a82615dafe1264e23c102235ac947fc21c6b121028b9f25e914b1fc20e830800076ba0fa5",
          "sha256": "0031044bc566808f3036fc8ec35db98cebcf2c5a676a80a6df2a3f20bd7199be",
          "sha1": "6512bab6ae4bb8424dde5d7d1dfa5bc2aec912b5",
          "md5": "31286d66a980b815712922fc031a7968"
        }
      ]
    }
  ]
}
