{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "local",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "local-0.1.0.aar",
          "url": "local-0.1.0.aar",
          "size": 1090,
          "sha512": "f397752cc191348b8712c8a57de7a3ee5d3d0ba0524aee73af4606de912c6745456fd3ae0e50b89c604607e0c9905e6c2db8bbc5aeb0d93baf9a179592edbf64",
          "sha256": "7ceaedccdc0dac9d77b02018480dc2c1dbaf3a0ab99cb4cf62d395fb139fbabc",
          "sha1": "e4e8f71a2916c2cc1fa79eeb5baae2162aed24cd",
          "md5": "80b6b833208ff010f5a682c2bbb8297e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "local-0.1.0.aar",
          "url": "local-0.1.0.aar",
          "size": 1090,
          "sha512": "f397752cc191348b8712c8a57de7a3ee5d3d0ba0524aee73af4606de912c6745456fd3ae0e50b89c604607e0c9905e6c2db8bbc5aeb0d93baf9a179592edbf64",
          "sha256": "7ceaedccdc0dac9d77b02018480dc2c1dbaf3a0ab99cb4cf62d395fb139fbabc",
          "sha1": "e4e8f71a2916c2cc1fa79eeb5baae2162aed24cd",
          "md5": "80b6b833208ff010f5a682c2bbb8297e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "local-0.1.0-sources.jar",
          "url": "local-0.1.0-sources.jar",
          "size": 5925,
          "sha512": "95027046a03c2c5460252e2219cde65fa570ab207760630536dc01a09cfec11636e12fe5cf8462f439edc16688af5f7e88804cb0bc02677b6bbc3905c421ef22",
          "sha256": "00c7ae02a79fc9108993d19b755b1aab4cb2941dd03f7a06e1d2ea7ebd55b955",
          "sha1": "07d09923d8e5014df4ea552a88f0eda30e03d02f",
          "md5": "2109b105214ebcbf93f2cbf8359dafa2"
        }
      ]
    }
  ]
}
