{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "commons",
    "version": "1.0.0-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0.0-snapshot.aar",
          "url": "commons-1.0.0-snapshot.aar",
          "size": 20377,
          "sha512": "b05d1076815adc0de0a12c73d6c7d0ea497ee01eb2b8e82a4e9c2f88e45ad23e0c78494f4d55d14c59de712b6635a2f3b3b8ca54fff4ef18e7461a7f2bff71f4",
          "sha256": "3d8cb9648c2236543955fde4efe992f605f7b25c9113cd7aa094f00948b17d17",
          "sha1": "a810976a9e4e8f5c5662bcaadd922986df09d6bf",
          "md5": "82d9619d7a9a1d2a0cb938bf1b007aa8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0.0-snapshot.aar",
          "url": "commons-1.0.0-snapshot.aar",
          "size": 20377,
          "sha512": "b05d1076815adc0de0a12c73d6c7d0ea497ee01eb2b8e82a4e9c2f88e45ad23e0c78494f4d55d14c59de712b6635a2f3b3b8ca54fff4ef18e7461a7f2bff71f4",
          "sha256": "3d8cb9648c2236543955fde4efe992f605f7b25c9113cd7aa094f00948b17d17",
          "sha1": "a810976a9e4e8f5c5662bcaadd922986df09d6bf",
          "md5": "82d9619d7a9a1d2a0cb938bf1b007aa8"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "commons-1.0.0-snapshot-sources.jar",
          "url": "commons-1.0.0-snapshot-sources.jar",
          "size": 10927,
          "sha512": "04a7883be400b5c08251a7bf54be85b865db1def5771fbe5836453a42bf42879a6b845da5abf3ca9501ae5848121ccd047fcf1d81b0c886387fdf2baa8a5fb88",
          "sha256": "4212fc7a20d39d462bf7c6bd700ebf24957635667d0cff99b18470436a8966bb",
          "sha1": "c86ff48bc7d3d9a0f4ab940edb69739fb7ac09c2",
          "md5": "3bcca35bd12cba90685f0eb13a1f7000"
        }
      ]
    }
  ]
}
