{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.6.aar",
          "url": "liveness2d-sdk-5.6.aar",
          "size": 2530964,
          "sha512": "7b5e6b0d57755f87d88fea598f713110fc8485d7d409fca66fb237e7125540515bf074514a6d42ed9a3e8d5dc350f8c69988b86c7221c8f49fc211850c55e675",
          "sha256": "8aa533da5a4a66caf6fb1f2ec756f1fcd4efc392535eb1190a1a342f0a8877ca",
          "sha1": "4a21e6bee7c7bbb1714d98c12c1443f42ef61ce3",
          "md5": "cd8df5b8dfed0e27a642a9c157f13e10"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.6.aar",
          "url": "liveness2d-sdk-5.6.aar",
          "size": 2530964,
          "sha512": "7b5e6b0d57755f87d88fea598f713110fc8485d7d409fca66fb237e7125540515bf074514a6d42ed9a3e8d5dc350f8c69988b86c7221c8f49fc211850c55e675",
          "sha256": "8aa533da5a4a66caf6fb1f2ec756f1fcd4efc392535eb1190a1a342f0a8877ca",
          "sha1": "4a21e6bee7c7bbb1714d98c12c1443f42ef61ce3",
          "md5": "cd8df5b8dfed0e27a642a9c157f13e10"
        }
      ]
    }
  ]
}
