{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "remote",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.1.0.aar",
          "url": "remote-0.1.0.aar",
          "size": 1091,
          "sha512": "d3cdfb4394c95bb00a79d64aa57fa64cc0076da616fb12ddbd5f8b096bd181c5768c97202cbd9677627086eeb6e6db993c906280717f20908c3e3c8986b5fa8e",
          "sha256": "59d4d28cf71acc19804ec4422d3e796f0d69e7b878dabd8fde7d6b9b8220dc0f",
          "sha1": "7b4faf43202d0314abac98426f1b0bddae436f0c",
          "md5": "dc5e5484434c729178e62219344d71e2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-0.1.0.aar",
          "url": "remote-0.1.0.aar",
          "size": 1091,
          "sha512": "d3cdfb4394c95bb00a79d64aa57fa64cc0076da616fb12ddbd5f8b096bd181c5768c97202cbd9677627086eeb6e6db993c906280717f20908c3e3c8986b5fa8e",
          "sha256": "59d4d28cf71acc19804ec4422d3e796f0d69e7b878dabd8fde7d6b9b8220dc0f",
          "sha1": "7b4faf43202d0314abac98426f1b0bddae436f0c",
          "md5": "dc5e5484434c729178e62219344d71e2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-0.1.0-sources.jar",
          "url": "remote-0.1.0-sources.jar",
          "size": 14111,
          "sha512": "ffeb0bc41fd559f2da48aace78e5c5ef07d5cbf331cbd65fa356845576045ac241b152234239abcdecd9f69961f9a393b7f38656a1733f11f92f67c40cdf102a",
          "sha256": "a41773f9b17740c8a9ef64bcd3889ce1640b391e0f924f9db36a8cb964c95912",
          "sha1": "ce867f3b1f7a05198578cb3cd9148121d7a85b66",
          "md5": "efb0c86a3fdf2420dea38ebf72855d93"
        }
      ]
    }
  ]
}
