{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "deviceIntelligence",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "deviceIntelligence-1.0.0.aar",
          "url": "deviceIntelligence-1.0.0.aar",
          "size": 97026,
          "sha512": "fdd7f88b4b2d9fba6cecbaa01ba2d94900d6092bbdfa146edd411c0601fcea2ff985cc6f38aa3bc03f77d5cea3322ab758987a5c85d054831c12c51d58e50ae9",
          "sha256": "a900ba603e2267d62a57cc70179841c3484824a726661db091bece12885a2ffa",
          "sha1": "02dbec750c74f10e2f98b6c06d7e2a929b355d98",
          "md5": "44d8d0ae8546deb78b8a4ce15cecabbc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "remote",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "local",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "deviceIntelligence-1.0.0.aar",
          "url": "deviceIntelligence-1.0.0.aar",
          "size": 97026,
          "sha512": "fdd7f88b4b2d9fba6cecbaa01ba2d94900d6092bbdfa146edd411c0601fcea2ff985cc6f38aa3bc03f77d5cea3322ab758987a5c85d054831c12c51d58e50ae9",
          "sha256": "a900ba603e2267d62a57cc70179841c3484824a726661db091bece12885a2ffa",
          "sha1": "02dbec750c74f10e2f98b6c06d7e2a929b355d98",
          "md5": "44d8d0ae8546deb78b8a4ce15cecabbc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "deviceIntelligence-1.0.0-sources.jar",
          "url": "deviceIntelligence-1.0.0-sources.jar",
          "size": 43659,
          "sha512": "aea1fc7320b5dea963039578ce8511bea3cab95d775136b1fd4f2daf18ccaf0881144b81a8bf00266cf888ad729612d39d6f1b1be0b4b48cbaef15b78ed62b4a",
          "sha256": "e73673a3e97af458e28b843f7048e4550415275d759a3f1acddbebbe282060c8",
          "sha1": "af02f2e8d3d6bdbd72f99bb91c4de6a00e579f93",
          "md5": "400d2adacd87f0f25a6dcc0ea507e4d1"
        }
      ]
    }
  ]
}
