{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.5.1.aar",
          "url": "liveness2d-sdk-5.5.1.aar",
          "size": 2535616,
          "sha512": "bbbabd614a8762d9ae4dc04816392a13d29879ab9b9bc78c77281d1c0f5a91d85b532773de70b38b43d8f15977d2e9edd5a09dcf8138439b4669b4d50fdfd6a6",
          "sha256": "9f884f02f76c5c2de3b1e0947b123ca714e93957fc8d122d1d7bc756e866149b",
          "sha1": "b1ffc173bf1bece887208d5ef73b8a61de2acb74",
          "md5": "32accae40d914c098654082de068cc0e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.5.1.aar",
          "url": "liveness2d-sdk-5.5.1.aar",
          "size": 2535616,
          "sha512": "bbbabd614a8762d9ae4dc04816392a13d29879ab9b9bc78c77281d1c0f5a91d85b532773de70b38b43d8f15977d2e9edd5a09dcf8138439b4669b4d50fdfd6a6",
          "sha256": "9f884f02f76c5c2de3b1e0947b123ca714e93957fc8d122d1d7bc756e866149b",
          "sha1": "b1ffc173bf1bece887208d5ef73b8a61de2acb74",
          "md5": "32accae40d914c098654082de068cc0e"
        }
      ]
    }
  ]
}
