{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "local",
    "version": "1.0.0-snapshot-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0-snapshot-2.aar",
          "url": "local-1.0.0-snapshot-2.aar",
          "size": 10530,
          "sha512": "4a6d4a6e313fd9987cc7e80cfbb0bcb0c494472484c7e0c1794040b4ba6a7bc5562a135feb029f43a531d582f898104d36febfd3163bfcb6a73c2d4aae3ad1bf",
          "sha256": "aafeb096e01796b16047f022d14952ec2e17fe44ff1abf5625ebcd420e8aa9ca",
          "sha1": "8337273986089606ca963a91c7df8bd0bde60313",
          "md5": "6e8195010ca22aa7a84c4678afc9c1f6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0-snapshot-2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "7.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0-snapshot-2.aar",
          "url": "local-1.0.0-snapshot-2.aar",
          "size": 10530,
          "sha512": "4a6d4a6e313fd9987cc7e80cfbb0bcb0c494472484c7e0c1794040b4ba6a7bc5562a135feb029f43a531d582f898104d36febfd3163bfcb6a73c2d4aae3ad1bf",
          "sha256": "aafeb096e01796b16047f022d14952ec2e17fe44ff1abf5625ebcd420e8aa9ca",
          "sha1": "8337273986089606ca963a91c7df8bd0bde60313",
          "md5": "6e8195010ca22aa7a84c4678afc9c1f6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "local-1.0.0-snapshot-2-sources.jar",
          "url": "local-1.0.0-snapshot-2-sources.jar",
          "size": 8672,
          "sha512": "1a2c8dcd9f404c5667498996c53c607135a771b38cf81695e74ec7aa4d3f288b7a02e8a65387e22c794029c96bfedcbbe29e6815afbb641e0224254b8ee4aad6",
          "sha256": "3d4f90c6d54f086d23fbec70cc66ab3c587ba26b0c68cd80720bf643e8b6caf4",
          "sha1": "250e52dd9ae4f2348a1448815f63eaf00af078fb",
          "md5": "ca3d9a61be8525b6cf761afd47409e97"
        }
      ]
    }
  ]
}
