{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.4.aar",
          "url": "liveness2d-sdk-5.4.aar",
          "size": 2522883,
          "sha512": "f46039842e888e96b5ccec68150c888d3f50190758656ccf49e56ced47e947c1320e939df3dccbb213b024cf780ff2ad799cb5bc8e0d5ee0fa1e5a39641c077f",
          "sha256": "243d4f7327c97e1e15d78982837c85a6c5e7d224279ae4f11b950f3ce76b2b1c",
          "sha1": "3484b2be4cc69a5636768c35ff1fb2b133b60779",
          "md5": "06655fa58e0e7b4c866d79abb7593821"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.4.aar",
          "url": "liveness2d-sdk-5.4.aar",
          "size": 2522883,
          "sha512": "f46039842e888e96b5ccec68150c888d3f50190758656ccf49e56ced47e947c1320e939df3dccbb213b024cf780ff2ad799cb5bc8e0d5ee0fa1e5a39641c077f",
          "sha256": "243d4f7327c97e1e15d78982837c85a6c5e7d224279ae4f11b950f3ce76b2b1c",
          "sha1": "3484b2be4cc69a5636768c35ff1fb2b133b60779",
          "md5": "06655fa58e0e7b4c866d79abb7593821"
        }
      ]
    }
  ]
}
