{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.6.0.aar",
          "url": "liveness2d-sdk-5.6.0.aar",
          "size": 2539183,
          "sha512": "11b593841910bfd2dbd0dcedcd4dda9178ad100e54b2ba6d87a18ad55d5fc5a4e15da1a1c731c269eaa49798f67ea4626f0df092ddfbecee5a94216275df7054",
          "sha256": "2f7a4c272a03f6231739350f52179471554c32598e6c76918086bad4ff8d6489",
          "sha1": "ceef42965f838745d0aee00ba393934bdec60189",
          "md5": "e06e1bbd64f7f8736fcf7f6311fd933d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.6.0.aar",
          "url": "liveness2d-sdk-5.6.0.aar",
          "size": 2539183,
          "sha512": "11b593841910bfd2dbd0dcedcd4dda9178ad100e54b2ba6d87a18ad55d5fc5a4e15da1a1c731c269eaa49798f67ea4626f0df092ddfbecee5a94216275df7054",
          "sha256": "2f7a4c272a03f6231739350f52179471554c32598e6c76918086bad4ff8d6489",
          "sha1": "ceef42965f838745d0aee00ba393934bdec60189",
          "md5": "e06e1bbd64f7f8736fcf7f6311fd933d"
        }
      ]
    }
  ]
}
