{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "commons",
    "version": "1.0.0-ofuscated-12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0.0-ofuscated-12.aar",
          "url": "commons-1.0.0-ofuscated-12.aar",
          "size": 20378,
          "sha512": "acda40107ded698c27ea94582b24858d8bb3e1d17fa1c3de50a131878f6ded1cd308b663e1c4392279da9a8e35f90b26d8520b85f9510627a1bbacdcc142ee47",
          "sha256": "b817cf67227762598bc99a7b2e98c2bc1b3277069b8e03e4b7e8717eb998a9cb",
          "sha1": "187d7d7e66374a8af4c7f6cded5e39e43936b5e6",
          "md5": "086826bc592cdc9cc8a84d85d44f1411"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.46"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "commons-1.0.0-ofuscated-12.aar",
          "url": "commons-1.0.0-ofuscated-12.aar",
          "size": 20378,
          "sha512": "acda40107ded698c27ea94582b24858d8bb3e1d17fa1c3de50a131878f6ded1cd308b663e1c4392279da9a8e35f90b26d8520b85f9510627a1bbacdcc142ee47",
          "sha256": "b817cf67227762598bc99a7b2e98c2bc1b3277069b8e03e4b7e8717eb998a9cb",
          "sha1": "187d7d7e66374a8af4c7f6cded5e39e43936b5e6",
          "md5": "086826bc592cdc9cc8a84d85d44f1411"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "commons-1.0.0-ofuscated-12-sources.jar",
          "url": "commons-1.0.0-ofuscated-12-sources.jar",
          "size": 10927,
          "sha512": "04a7883be400b5c08251a7bf54be85b865db1def5771fbe5836453a42bf42879a6b845da5abf3ca9501ae5848121ccd047fcf1d81b0c886387fdf2baa8a5fb88",
          "sha256": "4212fc7a20d39d462bf7c6bd700ebf24957635667d0cff99b18470436a8966bb",
          "sha1": "c86ff48bc7d3d9a0f4ab940edb69739fb7ac09c2",
          "md5": "3bcca35bd12cba90685f0eb13a1f7000"
        }
      ]
    }
  ]
}
