{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.7.0.aar",
          "url": "liveness2d-sdk-5.7.0.aar",
          "size": 2551976,
          "sha512": "6bdb02928ce70335156b8bce8daac3d87fe61000b4295404083c19794a269c4666a3074f4e0a6cfff82d314e75888825b890e3d764f80e91b01b5c30f372822b",
          "sha256": "fe11a00f428e773a091d42d2c674cdd1636c0a574a2d9ba0e412129d11e98212",
          "sha1": "b429dabf40d7e97eeed383f868d7b0afd1220668",
          "md5": "bf35db80a68b06486ec761bc1fcc2ed0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.7.0.aar",
          "url": "liveness2d-sdk-5.7.0.aar",
          "size": 2551976,
          "sha512": "6bdb02928ce70335156b8bce8daac3d87fe61000b4295404083c19794a269c4666a3074f4e0a6cfff82d314e75888825b890e3d764f80e91b01b5c30f372822b",
          "sha256": "fe11a00f428e773a091d42d2c674cdd1636c0a574a2d9ba0e412129d11e98212",
          "sha1": "b429dabf40d7e97eeed383f868d7b0afd1220668",
          "md5": "bf35db80a68b06486ec761bc1fcc2ed0"
        }
      ]
    }
  ]
}
