{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.3.aar",
          "url": "liveness2d-sdk-5.3.aar",
          "size": 2493971,
          "sha512": "4d2bd7b681182c2bbfa60a2453c6d0de020704dd553dd48cb6aacb5e54fee19346670fb8e6907e6a53631165cca3c3264a1b9da81bb449e6b4cd94c1f514975b",
          "sha256": "c4d3061bbb5dce2f3399a4caffb6887d547e3b044abff1208c778ef78dc32676",
          "sha1": "ac2d51df02cccc020034b8ffb988be72209e26f9",
          "md5": "2b8d6c1153cdc783bea128f990b38171"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.3.aar",
          "url": "liveness2d-sdk-5.3.aar",
          "size": 2493971,
          "sha512": "4d2bd7b681182c2bbfa60a2453c6d0de020704dd553dd48cb6aacb5e54fee19346670fb8e6907e6a53631165cca3c3264a1b9da81bb449e6b4cd94c1f514975b",
          "sha256": "c4d3061bbb5dce2f3399a4caffb6887d547e3b044abff1208c778ef78dc32676",
          "sha1": "ac2d51df02cccc020034b8ffb988be72209e26f9",
          "md5": "2b8d6c1153cdc783bea128f990b38171"
        }
      ]
    }
  ]
}
