{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.6.2.aar",
          "url": "liveness2d-sdk-5.6.2.aar",
          "size": 2544202,
          "sha512": "ba7d7cebeb5c6e25b4038ef3e7c8d3916c1fec0010d0abed202c1e1a4b5900ca10bb4c68197237bc3b4543696fe4df8238ced43e928336160e0ce318bb91c267",
          "sha256": "30f944ad654dc0d5b288394b288fba9c4e2cf262bc3c6cee1ea0b17c00a98c82",
          "sha1": "c5f776c46b2f6dad0da395a35c082cfc3052dbd9",
          "md5": "c5c74f225c524daeadaa1038fa77e60a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.6.2.aar",
          "url": "liveness2d-sdk-5.6.2.aar",
          "size": 2544202,
          "sha512": "ba7d7cebeb5c6e25b4038ef3e7c8d3916c1fec0010d0abed202c1e1a4b5900ca10bb4c68197237bc3b4543696fe4df8238ced43e928336160e0ce318bb91c267",
          "sha256": "30f944ad654dc0d5b288394b288fba9c4e2cf262bc3c6cee1ea0b17c00a98c82",
          "sha1": "c5f776c46b2f6dad0da395a35c082cfc3052dbd9",
          "md5": "c5c74f225c524daeadaa1038fa77e60a"
        }
      ]
    }
  ]
}
