{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.6.2.aar",
          "url": "liveness2d-sdk-5.6.2.aar",
          "size": 2544122,
          "sha512": "b52cca4cefca7a891f67181ee1b915ffb2fdb0dc0137bab69e268938d261b604238456906e7578ebf313ebf1f8d78668bcca25d6282a47bd9a608b5b6fe2e908",
          "sha256": "d09b86e48d03637cba96fa013d0388e10f67ef7b1e6c99ddfab23fd6984c6ef3",
          "sha1": "1421baa0c7d18962997c088e0ab9b1d2a7ba4152",
          "md5": "d41def441600ea31300a440cfabee26d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.6.2.aar",
          "url": "liveness2d-sdk-5.6.2.aar",
          "size": 2544122,
          "sha512": "b52cca4cefca7a891f67181ee1b915ffb2fdb0dc0137bab69e268938d261b604238456906e7578ebf313ebf1f8d78668bcca25d6282a47bd9a608b5b6fe2e908",
          "sha256": "d09b86e48d03637cba96fa013d0388e10f67ef7b1e6c99ddfab23fd6984c6ef3",
          "sha1": "1421baa0c7d18962997c088e0ab9b1d2a7ba4152",
          "md5": "d41def441600ea31300a440cfabee26d"
        }
      ]
    }
  ]
}
