{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "local",
    "version": "1.0.0-ofuscated-13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0-ofuscated-13.aar",
          "url": "local-1.0.0-ofuscated-13.aar",
          "size": 10544,
          "sha512": "60588e363b32d63870d7385d427b415595048b2ded601bd5624cf245342ccb2826ad161eb0ab8a24b0c6a542cb768a0d535773e32993e0114f59a6f3388abd78",
          "sha256": "d75ee16b9944625750674a5b02cc24c5ee69e51fb1db3324b8131f87c9573b45",
          "sha1": "77f872b073f24de08b26ad881d084ae62b8ec29c",
          "md5": "6158c4a98f1f3188b8501b82dd12b71c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "br.com.oiti.certiface",
          "module": "commons",
          "version": {
            "requires": "1.0.0-ofuscated-13"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.44"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "local-1.0.0-ofuscated-13.aar",
          "url": "local-1.0.0-ofuscated-13.aar",
          "size": 10544,
          "sha512": "60588e363b32d63870d7385d427b415595048b2ded601bd5624cf245342ccb2826ad161eb0ab8a24b0c6a542cb768a0d535773e32993e0114f59a6f3388abd78",
          "sha256": "d75ee16b9944625750674a5b02cc24c5ee69e51fb1db3324b8131f87c9573b45",
          "sha1": "77f872b073f24de08b26ad881d084ae62b8ec29c",
          "md5": "6158c4a98f1f3188b8501b82dd12b71c"
        }
      ]
    }
  ]
}
