{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-5.5.aar",
          "url": "liveness2d-sdk-5.5.aar",
          "size": 2530932,
          "sha512": "0987f76b6fd73366e6c548a5ec3e1d0d07a716b305e3d2e5af742316ecbb44a106f2b4b5a7ffb724af8e64c9f460678a34422ba2c246e05a693301093d05bf03",
          "sha256": "11c3e6768723dfb39e0236889c2d16e966aa1aaca24651ea501ce045390bb818",
          "sha1": "03e4411bc088179a94a61da62874a936c85c2d58",
          "md5": "6901713799366ba557c376b7684b738d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-5.5.aar",
          "url": "liveness2d-sdk-5.5.aar",
          "size": 2530932,
          "sha512": "0987f76b6fd73366e6c548a5ec3e1d0d07a716b305e3d2e5af742316ecbb44a106f2b4b5a7ffb724af8e64c9f460678a34422ba2c246e05a693301093d05bf03",
          "sha256": "11c3e6768723dfb39e0236889c2d16e966aa1aaca24651ea501ce045390bb818",
          "sha1": "03e4411bc088179a94a61da62874a936c85c2d58",
          "md5": "6901713799366ba557c376b7684b738d"
        }
      ]
    }
  ]
}
