{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti.certiface",
    "module": "remote",
    "version": "1.0.0-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-snapshot.aar",
          "url": "remote-1.0.0-snapshot.aar",
          "size": 21925,
          "sha512": "52d9d9f50f25aa49861692c5194649e5477c5e0363588cfcdef56affcf4ef73a802bf16fbe667c070321cb1729788675cdefaa63ada06804f5d5b12bc37bab9f",
          "sha256": "a48147d1bf435de7f8f9a614a09db78ecebd1a2a83c6f5af48a3a6e3dd3268b3",
          "sha1": "9d90ea773156b325fbfcb69f0a434ce297b69504",
          "md5": "8c67c037554c60d61ae5b0e98b2e6754"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.51.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "remote-1.0.0-snapshot.aar",
          "url": "remote-1.0.0-snapshot.aar",
          "size": 21925,
          "sha512": "52d9d9f50f25aa49861692c5194649e5477c5e0363588cfcdef56affcf4ef73a802bf16fbe667c070321cb1729788675cdefaa63ada06804f5d5b12bc37bab9f",
          "sha256": "a48147d1bf435de7f8f9a614a09db78ecebd1a2a83c6f5af48a3a6e3dd3268b3",
          "sha1": "9d90ea773156b325fbfcb69f0a434ce297b69504",
          "md5": "8c67c037554c60d61ae5b0e98b2e6754"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-1.0.0-snapshot-sources.jar",
          "url": "remote-1.0.0-snapshot-sources.jar",
          "size": 14111,
          "sha512": "ffeb0bc41fd559f2da48aace78e5c5ef07d5cbf331cbd65fa356845576045ac241b152234239abcdecd9f69961f9a393b7f38656a1733f11f92f67c40cdf102a",
          "sha256": "a41773f9b17740c8a9ef64bcd3889ce1640b391e0f924f9db36a8cb964c95912",
          "sha1": "ce867f3b1f7a05198578cb3cd9148121d7a85b66",
          "md5": "efb0c86a3fdf2420dea38ebf72855d93"
        }
      ]
    }
  ]
}
