{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.oiti",
    "module": "liveness2d-sdk",
    "version": "6.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "liveness2d-sdk-6.0.0.aar",
          "url": "liveness2d-sdk-6.0.0.aar",
          "size": 2552193,
          "sha512": "c9064d22b216d1afe5cd00859a3681ae8748d91cc6e28bb50baa890ddd1e7c40f6d7b33ed757a23bb8513a063a81ce15571f83b25d2aa1729a89d72bb7480d43",
          "sha256": "8ed3307d76b9268036cb43b0f7954cd3b8324b09d655551ed14780f754ce65b1",
          "sha1": "38f0dbf79bf09a03d73053a693d9e54fa6e99e20",
          "md5": "12e76e90a391dd3906c4e4d301455dd3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk16",
          "version": {
            "requires": "1.46"
          }
        }
      ],
      "files": [
        {
          "name": "liveness2d-sdk-6.0.0.aar",
          "url": "liveness2d-sdk-6.0.0.aar",
          "size": 2552193,
          "sha512": "c9064d22b216d1afe5cd00859a3681ae8748d91cc6e28bb50baa890ddd1e7c40f6d7b33ed757a23bb8513a063a81ce15571f83b25d2aa1729a89d72bb7480d43",
          "sha256": "8ed3307d76b9268036cb43b0f7954cd3b8324b09d655551ed14780f754ce65b1",
          "sha1": "38f0dbf79bf09a03d73053a693d9e54fa6e99e20",
          "md5": "12e76e90a391dd3906c4e4d301455dd3"
        }
      ]
    }
  ]
}
